# Generated by Django 3.2 on 2021-06-03 20:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210603_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='identification_announced_date',
            field=models.DateField(default=builtins.any, verbose_name='Data de Anúncio'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='identification_released_date',
            field=models.DateField(default=builtins.any, verbose_name='Data de Lançamento'),
        ),
    ]
