# Generated by Django 3.2 on 2021-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210603_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='identification_announced_date',
            field=models.DateField(default='2021-01-01', verbose_name='Data de Anúncio'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_released_date',
            field=models.DateField(default='2021-01-01', verbose_name='Data de Lançamento'),
        ),
    ]
