# Generated by Django 3.2 on 2021-06-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210603_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='identification_announced_date',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='identification_released_date',
        ),
    ]
