# Generated by Django 3.2 on 2021-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210603_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='display_resolution_ppi',
            field=models.IntegerField(default=0, verbose_name='Resolução de Tela (dpi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='display_resolution_ppi_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Score Display Ppi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='display_size_inches',
            field=models.IntegerField(default=0, verbose_name='Tamanho de Tela (polegadas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='display_size_inches_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Score Display Polegadas'),
            preserve_default=False,
        ),
    ]
