# Generated by Django 3.2 on 2021-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='identification_announced_date',
            field=models.DateField(default='2021-01-01', max_length=10, verbose_name='Data de Anúncio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='identification_released_date',
            field=models.DateField(default='2021-01-01', max_length=10, verbose_name='Data de Lançamento'),
            preserve_default=False,
        ),
    ]
