# Generated by Django 3.2 on 2021-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_produtos_display_type_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='sound_35mm_jack',
            new_name='sound_3_5mm_jack',
        ),
    ]
