# Generated by Django 3.2 on 2021-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_sound_35mm_jack_produtos_sound_3_5mm_jack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='battery_charging',
            field=models.CharField(max_length=256, verbose_name='Carregamento de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_music_play',
            field=models.CharField(max_length=256, verbose_name='Tempo de Reprodução de Música'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_standby',
            field=models.CharField(max_length=256, verbose_name='Bateria em Stand-by'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_type',
            field=models.CharField(max_length=256, verbose_name='Tipo de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_build',
            field=models.CharField(max_length=256, verbose_name='Construção'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_dimensions',
            field=models.CharField(max_length=256, verbose_name='Dimenções'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_other',
            field=models.CharField(max_length=256, verbose_name='Corpo Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_sim',
            field=models.CharField(max_length=256, verbose_name='SIM'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_weight',
            field=models.CharField(max_length=256, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_bluethoot',
            field=models.CharField(max_length=256, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_gps',
            field=models.CharField(max_length=256, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_nfc',
            field=models.CharField(max_length=256, verbose_name='NFC'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_radio',
            field=models.CharField(max_length=256, verbose_name='Radio'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_usb',
            field=models.CharField(max_length=256, verbose_name='Entrada USB'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_wlan',
            field=models.CharField(max_length=256, verbose_name='WLAN'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_other',
            field=models.CharField(max_length=256, verbose_name='Tela Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_protection',
            field=models.CharField(max_length=256, verbose_name='Proteção da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_resolution',
            field=models.CharField(max_length=256, verbose_name='Resolução da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size',
            field=models.CharField(max_length=256, verbose_name='Tamanho da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_type',
            field=models.CharField(max_length=256, verbose_name='Tipo de Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_type_technology',
            field=models.CharField(max_length=256, verbose_name='Tecnologia da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='features_other',
            field=models.CharField(max_length=256, verbose_name='Recursos Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='features_sensors',
            field=models.CharField(max_length=256, verbose_name='Sensores'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_announced',
            field=models.CharField(max_length=256, verbose_name='Anunciado'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_id',
            field=models.CharField(max_length=256, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_name',
            field=models.CharField(max_length=256, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_name_maker',
            field=models.CharField(max_length=256, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_released',
            field=models.CharField(max_length=256, verbose_name='Lançado'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_status',
            field=models.CharField(max_length=256, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_title',
            field=models.CharField(max_length=256, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_versions',
            field=models.CharField(max_length=256, verbose_name='Versões'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_features',
            field=models.CharField(max_length=256, verbose_name='Recursos da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_modules',
            field=models.CharField(max_length=256, verbose_name='Módulos da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_type',
            field=models.CharField(max_length=256, verbose_name='Tipo de Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_video',
            field=models.CharField(max_length=256, verbose_name='Vídeo da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_card_slot',
            field=models.CharField(max_length=256, verbose_name='Slot de Cartão de Memória'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_internal',
            field=models.CharField(max_length=256, verbose_name='Armazenamento Interno'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_other',
            field=models.CharField(max_length=256, verbose_name='Memória Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_colors',
            field=models.CharField(max_length=256, verbose_name='Cores'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_models',
            field=models.CharField(max_length=256, verbose_name='Modelos'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_price',
            field=models.CharField(max_length=256, verbose_name='Preços'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_sar_eu',
            field=models.CharField(max_length=256, verbose_name='SAR EU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_2g',
            field=models.CharField(max_length=256, verbose_name='Bandas 2G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_3g',
            field=models.CharField(max_length=256, verbose_name='Bandas 3G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_4g',
            field=models.CharField(max_length=256, verbose_name='Bandas 4G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_5g',
            field=models.CharField(max_length=256, verbose_name='Bandas 5G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_technology',
            field=models.CharField(max_length=256, verbose_name='Tecnologia'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_chipset',
            field=models.CharField(max_length=256, verbose_name='Processador'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_cpu',
            field=models.CharField(max_length=256, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_gpu',
            field=models.CharField(max_length=256, verbose_name='GPU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_os',
            field=models.CharField(max_length=256, verbose_name='Sistema Operacional'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_features',
            field=models.CharField(max_length=256, verbose_name='Recursos da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_modules',
            field=models.CharField(max_length=256, verbose_name='Módulos da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_type',
            field=models.CharField(max_length=256, verbose_name='Tipo de Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_video',
            field=models.CharField(max_length=256, verbose_name='Vídeo da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='sound_3_5mm_jack',
            field=models.CharField(max_length=256, verbose_name='Conector para Fone de Ouvido'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='sound_loudspeaker',
            field=models.CharField(max_length=256, verbose_name='Alto-falante(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_battery_life',
            field=models.CharField(max_length=256, verbose_name='Testes de Vida de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_loudspeaker',
            field=models.CharField(max_length=256, verbose_name='Testes de Alto-falante(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_performance',
            field=models.CharField(max_length=256, verbose_name='Testes de Performance'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_size',
            field=models.CharField(max_length=256, verbose_name='Capacidade da bateria'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_size_unit',
            field=models.CharField(max_length=256, verbose_name='Capaciadade da bateria (unidade)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_type',
            field=models.CharField(max_length=256, verbose_name='Tipo de bateria'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='body',
            field=models.CharField(max_length=256, verbose_name='Corpo'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_pixels',
            field=models.CharField(max_length=256, verbose_name='Resolução da Câmera'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_pixels_unit',
            field=models.CharField(max_length=256, verbose_name='Resolução da Câmera (unidade)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='chipset_short',
            field=models.CharField(max_length=256, verbose_name='Processador'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_size_pixels',
            field=models.CharField(max_length=256, verbose_name='Tamanho da tela (pixels)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='maker',
            field=models.CharField(max_length=256, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os',
            field=models.CharField(max_length=256, verbose_name='Sistema operacional'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_size',
            field=models.CharField(max_length=256, verbose_name='Memória RAM'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_size_unit',
            field=models.CharField(max_length=256, verbose_name='Memória RAM (unidade)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.CharField(max_length=256, verbose_name='Armazenamento'),
        ),
    ]
