# Generated by Django 3.2 on 2021-06-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210603_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_modules',
            field=models.TextField(max_length=512, verbose_name='Módulos da Câmera Principal'),
        ),
    ]
