# Generated by Django 3.2 on 2021-06-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_produtos_main_camera_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='battery_music_play',
            field=models.CharField(max_length=256, null=True, verbose_name='Tempo de Reprodução de Música'),
        ),
    ]
