# Generated by Django 3.2 on 2021-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_produtos_battery_music_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='battery_charging',
            field=models.CharField(max_length=256, null=True, verbose_name='Carregamento de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Battery Score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_standby',
            field=models.CharField(max_length=256, null=True, verbose_name='Bateria em Stand-by'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_type_mah',
            field=models.IntegerField(null=True, verbose_name='Capacidade de Bateria (mAh)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='battery_type_mah_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Battery MAh'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_build',
            field=models.CharField(max_length=256, null=True, verbose_name='Construção'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_dimensions',
            field=models.CharField(max_length=256, null=True, verbose_name='Dimenções'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_other',
            field=models.CharField(max_length=256, null=True, verbose_name='Corpo Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_sim',
            field=models.CharField(max_length=256, null=True, verbose_name='SIM'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='body_weight',
            field=models.CharField(max_length=256, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='camera_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Camera Score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_bluethoot',
            field=models.CharField(max_length=256, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_gps',
            field=models.CharField(max_length=256, null=True, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_nfc',
            field=models.CharField(max_length=256, null=True, verbose_name='NFC'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_radio',
            field=models.CharField(max_length=256, null=True, verbose_name='Radio'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_usb',
            field=models.CharField(max_length=256, null=True, verbose_name='Entrada USB'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comms_wlan',
            field=models.CharField(max_length=256, null=True, verbose_name='WLAN'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_other',
            field=models.CharField(max_length=256, null=True, verbose_name='Tela Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_protection',
            field=models.CharField(max_length=256, null=True, verbose_name='Proteção da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_resolution',
            field=models.CharField(max_length=256, null=True, verbose_name='Resolução da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_resolution_ppi',
            field=models.IntegerField(null=True, verbose_name='Resolução de Tela (dpi, null=True)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_resolution_ppi_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Display Ppi'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Display Score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size',
            field=models.CharField(max_length=256, null=True, verbose_name='Tamanho da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size_inches',
            field=models.IntegerField(null=True, verbose_name='Tamanho de Tela (polegadas, null=True)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size_inches_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Display Polegadas'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size_screentobody_ratio',
            field=models.IntegerField(null=True, verbose_name='Relação Corpo Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_size_screentobody_ratio_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Display Relação'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo de Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_type_technology',
            field=models.CharField(max_length=256, null=True, verbose_name='Tecnologia da Tela'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_type_technology_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Display Tech'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='features_other',
            field=models.CharField(max_length=256, null=True, verbose_name='Recursos Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='features_sensors',
            field=models.CharField(max_length=256, null=True, verbose_name='Sensores'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_announced',
            field=models.CharField(max_length=256, null=True, verbose_name='Anunciado'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_announced_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Data de Anúncio'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_released',
            field=models.CharField(max_length=256, null=True, verbose_name='Lançado'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_released_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_status',
            field=models.CharField(max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_title',
            field=models.CharField(max_length=256, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='identification_versions',
            field=models.CharField(max_length=256, null=True, verbose_name='Versões'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_features',
            field=models.CharField(max_length=256, null=True, verbose_name='Recursos da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_modules',
            field=models.TextField(max_length=512, null=True, verbose_name='Módulos da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_modules_mp',
            field=models.IntegerField(null=True, verbose_name='Resolução de Câmera Principal (MP)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_modules_mp_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Score Câmera MP'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo de Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='main_camera_video',
            field=models.CharField(max_length=256, null=True, verbose_name='Vídeo da Câmera Principal'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_card_slot',
            field=models.CharField(max_length=256, null=True, verbose_name='Slot de Cartão de Memória'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_internal',
            field=models.CharField(max_length=256, null=True, verbose_name='Armazenamento Interno'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='memory_other',
            field=models.CharField(max_length=256, null=True, verbose_name='Memória Outro(s)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_colors',
            field=models.CharField(max_length=256, null=True, verbose_name='Cores'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_models',
            field=models.CharField(max_length=256, null=True, verbose_name='Modelos'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_price',
            field=models.CharField(max_length=256, null=True, verbose_name='Preços'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='misc_sar_eu',
            field=models.CharField(max_length=256, null=True, verbose_name='SAR EU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_2g',
            field=models.CharField(max_length=256, null=True, verbose_name='Bandas 2G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_3g',
            field=models.CharField(max_length=256, null=True, verbose_name='Bandas 3G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_4g',
            field=models.CharField(max_length=256, null=True, verbose_name='Bandas 4G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_bands_5g',
            field=models.CharField(max_length=256, null=True, verbose_name='Bandas 5G'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='network_technology',
            field=models.CharField(max_length=256, null=True, verbose_name='Tecnologia'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='performance_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Performance Score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_chipset',
            field=models.CharField(max_length=256, null=True, verbose_name='Processador'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_cpu',
            field=models.CharField(max_length=256, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_gpu',
            field=models.CharField(max_length=256, null=True, verbose_name='GPU'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='platform_os',
            field=models.CharField(max_length=256, null=True, verbose_name='Sistema Operacional'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_features',
            field=models.CharField(max_length=256, null=True, verbose_name='Recursos da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_modules',
            field=models.CharField(max_length=256, null=True, verbose_name='Módulos da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo de Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='selfie_camera_video',
            field=models.CharField(max_length=256, null=True, verbose_name='Vídeo da Câmera Selfie'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='sound_3_5mm_jack',
            field=models.CharField(max_length=256, null=True, verbose_name='Conector para Fone de Ouvido'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='sound_loudspeaker',
            field=models.CharField(max_length=256, null=True, verbose_name='Alto-falante(s, null=True)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_battery_life',
            field=models.CharField(max_length=256, null=True, verbose_name='Testes de Vida de Bateria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_loudspeaker',
            field=models.CharField(max_length=256, null=True, verbose_name='Testes de Alto-falante(s, null=True)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tests_performance',
            field=models.CharField(max_length=256, null=True, verbose_name='Testes de Performance'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='vaibo_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Vaibo Score'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_size',
            field=models.CharField(max_length=256, null=True, verbose_name='Capacidade da bateria'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_size_unit',
            field=models.CharField(max_length=256, null=True, verbose_name='Capaciadade da bateria (unidade, null=True)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo de bateria'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='body',
            field=models.CharField(max_length=256, null=True, verbose_name='Corpo'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_pixels',
            field=models.CharField(max_length=256, null=True, verbose_name='Resolução da Câmera'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_pixels_unit',
            field=models.CharField(max_length=256, null=True, verbose_name='Resolução da Câmera (unidade, null=True)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='chipset_short',
            field=models.CharField(max_length=256, null=True, verbose_name='Processador'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(max_length=256, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_size_pixels',
            field=models.CharField(max_length=256, null=True, verbose_name='Tamanho da tela (pixels, null=True)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os',
            field=models.CharField(max_length=256, null=True, verbose_name='Sistema operacional'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_size',
            field=models.CharField(max_length=256, null=True, verbose_name='Memória RAM'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_size_unit',
            field=models.CharField(max_length=256, null=True, verbose_name='Memória RAM (unidade, null=True)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.CharField(max_length=256, null=True, verbose_name='Armazenamento'),
        ),
    ]
