# Generated by Django 3.2 on 2021-06-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210603_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
