# Generated by Django 3.2 on 2021-06-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
