# Generated by Django 3.2 on 2021-06-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
