# Generated by Django 3.2 on 2021-06-04 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210604_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='battery_score',
            field=models.CharField(max_length=10, null=True, verbose_name='Battery_score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='camera_score',
            field=models.CharField(max_length=10, null=True, verbose_name='Camera_score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='display_score',
            field=models.CharField(max_length=10, null=True, verbose_name='Display_score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('05eb3358-8966-4f37-8c8b-af7ae7c9b67f'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='performance_score',
            field=models.CharField(max_length=10, null=True, verbose_name='Performance_score'),
        ),
    ]
