# Generated by Django 3.2.4 on 2021-06-17 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210604_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='client_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Cliente Score'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='expert_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Expert Score'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('200da969-c08b-4289-b02b-34bb22b1b5c0'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
