# Generated by Django 3.2.4 on 2021-06-17 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210616_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('926ef529-3c87-4a5a-804f-779a057829e3'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
