# Generated by Django 3.2.4 on 2021-06-22 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210616_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('idendification_id', models.CharField(max_length=255, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
                ('attscore', models.IntegerField(null=True, verbose_name='Att Score')),
                ('attscore_percent', models.CharField(max_length=10, null=True, verbose_name='Att Score(%)')),
                ('performance', models.IntegerField(null=True, verbose_name='Performance')),
                ('screen', models.IntegerField(null=True, verbose_name='Tela')),
                ('design', models.IntegerField(null=True, verbose_name='Design')),
                ('price', models.IntegerField(null=True, verbose_name='Preço')),
                ('battery', models.IntegerField(null=True, verbose_name='Battery')),
                ('reliability', models.IntegerField(null=True, verbose_name='Confiabilidade')),
                ('durability', models.IntegerField(null=True, verbose_name='Durabilidade')),
                ('portability', models.IntegerField(null=True, verbose_name='Portabilidade')),
                ('usability', models.IntegerField(null=True, verbose_name='Usabilidade')),
                ('size', models.IntegerField(null=True, verbose_name='Tamanho')),
                ('sound', models.IntegerField(null=True, verbose_name='Som')),
            ],
            options={
                'verbose_name': 'ProdutoAtt',
                'verbose_name_plural': 'ProdutosAtt',
            },
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('72c1c2f4-3b28-4275-9792-4e1cb825037d'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
