# Generated by Django 3.2.4 on 2021-06-22 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210622_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosatt',
            name='camera',
            field=models.IntegerField(null=True, verbose_name='Câmera'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('52909da9-f0e8-4f96-b9a5-0cfd06c8d96a'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
