# Generated by Django 3.2.4 on 2021-06-22 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210622_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtosatt',
            old_name='idendification_id',
            new_name='identification_id',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('f754580e-74e0-4e8c-b477-c14278713a54'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
