# Generated by Django 3.2.4 on 2021-06-22 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210622_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.CharField(default=uuid.UUID('c3d8c773-896f-4fb3-84e9-76b9b30783f7'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produtosatt',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
